### PR TITLE
Russian locale fixes

### PR DESCRIPTION
**Pull request by chromKa**
new rus

### CODE REVIEW

**Comment by pierre-josselin** [comment]
Thank you!
Are you *thejuves* or are you someone else? (for credits)

**Comment by chromKa** [comment]
I'm translator full Ultimate Trainer 5, if you remember. I was waiting for the update of version 5, and was surprised when version 6 came out and someone had already translated it before me. In this commit, I corrected the mistakes and translated what was not translated.

**Comment by pierre-josselin** [comment]
Yes I remember, thanks for that!

**Comment by thejuves** [comment]
Need to remove one letter in this translation)

**main.json**
```javascript
 "offshore_money": "Офшоpные деньги",
```

**Comment by pierre-josselin** [comment]
@thejuves Thank you, fixed by @chromKa in [this commit](https://github.com/chromKa/payday-2-ultimate-trainer-6/commit/e60d5b3964d87f2fdd9e17bf94cee55d533b0129) (pending PR).

**Pull request merged**
